# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-30 15:02
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelsTrackingFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=128, verbose_name='مدل')),
                ('tracking_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), default=[], size=None, verbose_name='فیلد\u200cهای قابل نمایش در تاریخچه')),
            ],
            options={
                'verbose_name': 'مدل و فیلدهای قابل نمایش در تاریخچه',
                'verbose_name_plural': 'مدل\u200cها و فیلدهای قابل نمایش در تاریخچه',
            },
        ),
    ]
